# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(auto_created=True, blank=True, max_length=15, null=True)),
                ('telephone', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
