# Generated by Django 2.2.3 on 2019-10-24 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trips', to='home.TravelTime'),
        ),
    ]
